### ISSUE TITLE
TypeError: Unknown format for file data/wghs/6.dat for MASW module

### ISSUE THREAD

**Issue by alangi** [jpvantassel/swprocess#10]
I'm getting an error with the MASW that seems to be related to the .dat example files. Please see attached file with full error message

[new 2.txt](https://github.com/jpvantassel/swprocess/files/9933450/new.2.txt)

**Comment by jpvantassel** [comment]
Hi @alangi,
What version of Python are you using?

**Comment by alangi** [comment]
3.10

**Comment by jpvantassel** [comment]
@alangi and what version of the obspy package are you using?

**Comment by alangi** [comment]
Package            Version
------------------ -----------
certifi            2022.9.24
charset-normalizer 2.1.1
contourpy          1.0.6
cycler             0.11.0
decorator          5.1.1
fonttools          4.38.0
greenlet           2.0.0.post0
idna               3.4
importlib-metadata 5.0.0
kiwisolver         1.4.4
llvmlite           0.39.1
lxml               4.9.1
matplotlib         3.6.2
numba              0.56.3
numpy              1.23.4
obspy              1.3.1
packaging          21.3
pandas             1.5.1
Pillow             9.3.0
pip                20.2.1
pyparsing          3.0.9
PyQt5              5.15.7
PyQt5-Qt5          5.15.2
PyQt5-sip          12.11.0
python-dateutil    2.8.2
pytz               2022.6
requests           2.28.1
scipy              1.9.3
setuptools         49.2.1
sigpropy           1.0.0
six                1.16.0
SQLAlchemy         1.4.42
swprepost          2.0.0
swprocess          0.1.1
urllib3            1.26.12
zipp               3.10.0

**Comment by alangi** [comment]
I think that I fixed it. It would probably have been obspy 1.3.1 with either python 3.8.5 or python 3.10.
I worked out that jupyter wasn't using the correct kernel as I was running in a virtual environment. I've fixed that up now.

By the way, do you still have access to your old ut email? I was going to get in touch via that, but heard that you have moved.

**Comment by jpvantassel** [comment]
Hi @alangi,
Glad you got things working. Yes, I have moved from UT; at least for the time being opening a GitHub issue is the best way to get a hold of me for code-related questions. It also allows others in the community to benefit from our discussion.
