### ISSUE TITLE
processing already stacked MASW data 

### ISSUE THREAD

**Issue by akpopoola** [jpvantassel/swprocess#12]
Hi Joseph,

I was trying to use your software to process active MASW data. Each offset is already stacked I was getting error at the "Analysis" section of the jupyter notebook. I know you mentioned the input is unstacked shot record at each shot location. Is there any walk around for using already stacked data?

**Comment by jpvantassel** [comment]
Hi @akpopoola,
You should be able to run your analysis with pre-stacked data. What is the error you are seeing? Please post the full trace back.

**Comment by akpopoola** [comment]
I have SU file format. Just as walkaround, I duplicated each offset's files 3 times to mimic multiple shots. I still get error which I think this time has to do with the file header. The error msg is attached.

[error_msg.txt](https://github.com/jpvantassel/swprocess/files/9992554/error_msg.txt)
![sample_shot_record](https://user-images.githubusercontent.com/4508631/201403877-a533055b-93b1-4105-bb89-6b60e5edc5c7.png)

**Comment by jpvantassel** [comment]
Hi @akpopoola,

The issue you are seeing is related to an incorrectly set header variable (see error message for variable name) in the SU file and not an issue with _swprocess_. It is also unrelated to using pre-stacked data. You will need to fix your SU files header before you can move forward. While with a little coding you can use _swprocess_ to repair your files header, you may find it easier to use a GUI-based tool like _geopsy_.

All the best,
Joe
