### ISSUE TITLE
Installing on Mac M1

### ISSUE THREAD

**Issue by rifasuhaz** [jpvantassel/swprocess#15]
I am trying to install swprocess on a Mac M1 device. But the machine does not support PyQt5. I tried installing it by changing the dependency to PyQt6. Even though it was successfully installed, I cannot run codes. Is swprocess not supported by PyQt6? Is there any alternative to installing swprocess?

**Comment by jpvantassel** [comment]
Hi @rifasuhaz,

If you found a solution to this issue, please share your solution. This helps to benefit others in the community, who may be encountering a similar problem.

Thanks,
Joe

**Comment by rifasuhaz** [comment]
Changing the dependency to PyQt6 didn't work. I was trying to install PyQt5 to a conda environment, which wasn't successful. Installing it to a venv from the terminal in rosetta mode(arch -x86_64) worked. The solution is at this [thread](https://stackoverflow.com/a/68038451).

With regards,
Rifa
