### ISSUE TITLE
Set a condition to deal with STACK not being present in sg2 files

### ISSUE THREAD

**Issue by alangi** [jpvantassel/swprocess#16]
The file format that my system puts out does not include the STACK object in the header. This creates an issue with sensor1c.py when trying to import the data.

For now I have just deleted the line, but having a condition in there to deal with missing header objects may be beneficial.

**Comment by jpvantassel** [comment]
Hi @alangi,
Would you be willing to share a copy of that file either here or privately with me via email? I would like to add it to my set of test conditions.
Thanks,
Joe

**Comment by alangi** [comment]
Sent via email. I can't upload the files here without altering the suffix

**Comment by jpvantassel** [comment]
@alangi Can you try using the latest verison of the code on the `dev` branch https://github.com/jpvantassel/swprocess/commit/780b00be7dd6c063af077a6ab460097517559b40? I believe I fixed the issue of a header variable not being set by catching it and setting a default, but the issue of an incorrect header value is more challenging and still returns an error. Thanks!

**Comment by jpvantassel** [comment]
@MohamedYasser24 this thread is related to header data STACK not being preset in a SEG2 file if you have another question or request please open a separate issue.

**Comment by jpvantassel** [comment]
I believe this issue is resolved with release v0.3.0, closing the issue.
