### ISSUE TITLE
Stats Notebook Running Time

### ISSUE THREAD

**Issue by EnyiK** [jpvantassel/swprocess#19]
Hi Joe, 

I have been trying to run the stats notebook on Designsafe as well as my school's HPC but I when I run the section "Launch" for the trimming, it just keeps running for hours non-stop and there is no error message.  Is that normal or could I be doing something wrong?

Thanks.

**Comment by jpvantassel** [comment]
@EnyiK,

Interactive trimming should be almost instantaneous. You need to: select the points you want to remove, then select a box with no points to indicate you are done, then respond to the input prompt on Jupyter. Hope this helps.
