### ISSUE TITLE
Name error - swprocess 

### ISSUE THREAD

**Issue by cmbmayer** [jpvantassel/swprocess#25]
Hello Joe, I am playing around with swprocess (right after taking the course last week), and ended up getting an error during the analysis stage. 
I started in the swprocess.ipnyb but instead of loading the practice data, I directed to another folder with new data. 
I get "NameError: name 'swprocess' is not defined"

Interestingly I reran the code but directed it to the example data - that worked.
Not sure what i am doing wrong. I attached a screenshot. thanks. 
![swprocess - name error](https://github.com/user-attachments/assets/4cb85cf5-8ae2-4cca-834a-0cd248088d56)

**Comment by cmbmayer** [comment]
I was able to figure this out. Needed to direct the input to the folder and include \data to the end of path. thanks

**Comment by jpvantassel** [comment]
Glad you got it resolved!
