### ISSUE TITLE
Preparing DAS data

### ISSUE THREAD

**Issue by HarryWhitelam** [jpvantassel/swprocess#27]
Hi @jpvantassel. 

Thank you for the package, it looks really useful. This is a slightly open-ended question, but in your papers, you've used _swprocess_ for DAS data without converting to particle velocities. I am struggling to get DAS data into an _Array1D_ object. Do you have any standard operations or prep that need to be applied to the DAS data before it can be imported - such as adding header variables? 

I think my problem at the moment is with how I'm converting from TDMS to SEGY files so I won't add that here, but if I make any progress I may add some of the code & errors I'm getting from _swprocess_. 

Thanks for your time,
Harry

**Comment by jpvantassel** [comment]
Hi @HarryWhitelam,

Yes, in our papers we extracted our DAS data into some standard geophysical format (SEGY, SEG2, or SU as _swprocess_ can read any of these). So one option is to try that first. I would recommend using SU as it can be written by obspy, [here](https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.write.html) is some information on that. Another thing to try is if you can create an Array1D out of your data you can use the [`to_file`](https://swprocess.readthedocs.io/en/latest/array1d.html#swprocess.array1d.Array1D) method to write it out to the SU format with the appropriate headers filled out.

Hope this helps,
Joe
