### ISSUE TITLE
About the use of the software

### ISSUE THREAD

**Issue by Qmbnowhere** [jpvantassel/swprocess#30]
Hello, sorry to bother you, is there a manual about this software, such as data input, workflow, wavefield transform, frequency dispersion, etc., thank you very much!

**Comment by jpvantassel** [comment]
Hi @Qmbnowhere,
The workflow is explained in the open-access paper by Vantassel and Cox (2022) [here](https://doi.org/10.1007/s10950-021-10035-y). The software is documentation is hosted on ReadTheDocs [here](https://swprocess.readthedocs.io/en/latest/?badge=latest). The provided examples [here](https://github.com/jpvantassel/swprocess/tree/main/examples) also include some explanatory information.

**Comment by Qmbnowhere** [comment]
Hi,@jpvantassel,
Thank you very much and I wish you good health and success in your work.
