### ISSUE TITLE
Error in running the code create_su.ipynb

### ISSUE THREAD

**Issue by AniketSanjayDesai** [jpvantassel/swprocess#4]
Dear Joseph

Hello,
I am Aniket Desai from the Indian Institute of Technology, Roorkee, India. 

While running the code create_su.ipynb, it shows the error '[Errno 2] No such file or directory: 'set00.csv''. (Figure attached).
I guess this .csv files are missing in the folders model_0, model_1, model_2 and model_3. I request you to provide these files.

Also, I have velocity time histories from 24 receivers as an output of MASW (.xlsx format, 24 columns). How can I use masw.ipynb code for it to generate dispersion image using different methods ("fk", "slantstack", "phaseshift", "fdbf" etc.) or how can I convert it to seg2 or SU data format?

![Error_create_su](https://user-images.githubusercontent.com/42245671/182022393-18154731-973f-49e2-bd64-25d218e549d9.jpg)

**Comment by jpvantassel** [comment]
Hi @AniketSanjayDesai,

The notebook `create_su.ipynb` is not part of the _swprocess_ public API, but rather a utility for parsing .csv files in a specific format (in this case results from a finite element analysis wave propagation simulation). In lieu of providing the raw `.csv` files (which in this case are quite large) I provide the resulting SU files (see for example [46m_2m_-10m.su](https://github.com/jpvantassel/swprocess/blob/main/benchmarks/model_0/46m_2m_-10m.su)). You can then use these SU files to reproduce the MASW benchmarks if you wish.

Regarding your second question about performing MASW using data in a CSV file, please create a separate issue. Creating a separate issue with a related title helps other interested users to easily find your question and benefit from the answer.

All the best,
Joe
