### ISSUE TITLE
Generating dispersion image using .xlsx file

### ISSUE THREAD

**Issue by AniketSanjayDesai** [jpvantassel/swprocess#5]
Hello Joseph

I have velocity time histories from 24 receivers as an output of MASW (.xlsx format, 24 columns). How can I use masw.ipynb code for it to generate dispersion image using different methods ("fk", "slantstack", "phaseshift", "fdbf" etc.) or how can I convert it to seg2 or SU data format?

**Comment by jpvantassel** [comment]
Hi @AniketSanjayDesai,

The procedure to generate a dispersion image using `swprocess` from time histories stored in an `.xlsx` file is as follows:

1). Load your `.xlsx` data into Python. I would recommend converting your `.xlsx` to `.csv` and then use `pandas` `read_csv` function, but there are many ways to do this.
2). Create a [`Sensor1C`](https://swprocess.readthedocs.io/en/latest/sensor1c.html#module-swprocess.sensor1c) object for each column of your data. Be sure to include appropriate metadata (e.g., sensor position, time step, etc.).
3). Create a [`Source`](https://swprocess.readthedocs.io/en/latest/source.html#module-swprocess.source) object with the appropriate `x`, `y`, and `z` positions.
4). Create an [`Array1D`](https://swprocess.readthedocs.io/en/latest/array1d.html#module-swprocess.array1d) object from the list of 24 `Sensor1C` objects and `Source` object. 
5). Write the data to `SU` format using the `.to_file` method of `Array1D`.
6). Use the standard MASW workflow with the generated `SU` file.

All the best,
Joe
