### ISSUE TITLE
Number of output dispersion points

### ISSUE THREAD

**Issue by seguj** [jpvantassel/swprocess#6]
Dear, Joseph

Hello,
This is Youngjun Jeon from Korea University, again.

I trimmed dispersion data following the example script.
Now I'm looking for how to adjust the number of extracted dispersion points (final output).

If you don't mind, can you let me know which code (or *.py file) should I modify for the adjustment?

Best regards,
Youngjun

**Comment by jpvantassel** [comment]
Hi @seguj,

I am not sure what you mean by `adjust the number of extracted dispersion points`, can you please clarify?

All the best,
Joe

**Comment by seguj** [comment]
Dear Joseph,

Oh sorry for the confusion.
When after trimming, I could get resampled dispersion points with its error bar.
But what I want to do is to get more data points not only determined by the code.

if it is not clear yet let me know.
And sorry for the confuson again.

Thanks .

**Comment by jpvantassel** [comment]
Hi @seguj,

I believe you are asking how to get more points in the experimental dispersion data (i.e., calculate your summary statistics at a closer spacing). To do this you need to change the number of points (i.e., variable `nx`) in the cell labeled __Input__ in the `stats.ipynb` example.

All the best,
Joe
