### ISSUE TITLE
Error in running the code vis_model_0.ipynb

### ISSUE THREAD

**Issue by AniketSanjayDesai** [jpvantassel/swprocess#8]
Hello Joseph

While running the code vis_model_0.ipynb, it shows an error(attached error_3) during obtaining the analytical solution. Kindly let me know what to do.

![Error_3](https://user-images.githubusercontent.com/42245671/191229966-3f9db8a3-e304-45d9-bc2b-123a007cd8b0.JPG)

**Comment by jpvantassel** [comment]
The benchmark notebooks are provided for demonstration purposes only and are not meant to be run by users.
