### ISSUE TITLE
Extraction of the picked dispersion curve data

### ISSUE THREAD

**Issue by AniketSanjayDesai** [jpvantassel/swprocess#9]
Hello Joseph

I ran the code vis_model_0.ipynb and generated the dispersion images using various methods. It also shows the picked dispersion curve from the dispersion image. I want to extract the data of the points on the picked dispersion curve in .xls or .txt format. Kindly let me know how to do that.

**Comment by jpvantassel** [comment]
The benchmark notebooks are provided for demonstration purposes only and are not meant to be run by users.
